# Generated by Django 2.2.12 on 2021-07-10 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='this_user_fav_listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
