# Generated by Django 2.2.12 on 2021-07-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210710_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='imageurl',
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
