# Generated by Django 2.2.12 on 2021-07-12 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='dateposted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
