# Generated by Django 2.2.12 on 2021-07-13 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210712_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='datebidded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
